[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/create-checkout"
  to = "/.netlify/functions/create-checkout"
  status = 200

[[redirects]]
  from = "/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

[[redirects]]
  from = "/donate-success"
  to = "/index.html"
  status = 200
